services:
  assistify:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    container_name: assistify
    command: mix phx.server
    depends_on:
      - assistify_db
    ports:
      - 4000:4000
    volumes:
      - .:/app
    networks:
      - assistify_net

  assistify_db:
    image: "postgres:13"
    container_name: assistify_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "assistify_db:/var/lib/postgresql/data"
    networks:
      - assistify_net

volumes:
  assistify_db:

networks:
  assistify_net:
    name: assistify_net
